"""Iteration state dataclass for tracking multi-agent workflow state."""

from dataclasses import dataclass, field
from typing import Dict, Optional
from datetime import datetime


@dataclass
class IterationState:
    """Represents the complete state of a single iteration.
    
    This dataclass captures all information from one cycle of the
    multi-agent review process:
    - Presenter output
    - Individual reviewer feedback
    - Aggregated board decision
    - Confidence score
    - Human approval status
    
    Attributes:
        iteration: Iteration number (1-indexed)
        presenter_output: Content generated by presenter agent
        reviewer_feedback: Dict mapping reviewer role to their feedback string
        aggregated_feedback: Unified feedback from aggregator agent
        confidence: Confidence score (0.0 to 1.0)
        approved: Whether human has approved this iteration
        timestamp: When iteration was created
        error: Error message if iteration failed
    """
    
    iteration: int
    presenter_output: str
    reviewer_feedback: Dict[str, str] = field(default_factory=dict)
    aggregated_feedback: str = ""
    confidence: float = 0.0
    approved: bool = False
    timestamp: datetime = field(default_factory=datetime.now)
    error: Optional[str] = None
    
    def is_approved(self) -> bool:
        """Check if iteration is approved by human.
        
        Returns:
            True if approved, False otherwise
        """
        return self.approved
    
    def has_error(self) -> bool:
        """Check if iteration has an error.
        
        Returns:
            True if error occurred, False otherwise
        """
        return self.error is not None
    
    def meets_confidence_threshold(self, threshold: float = 0.82) -> bool:
        """Check if confidence meets threshold.
        
        Args:
            threshold: Minimum confidence required (default 0.82)
            
        Returns:
            True if confidence >= threshold, False otherwise
        """
        return self.confidence >= threshold
    
    def to_dict(self) -> Dict:
        """Convert iteration state to dictionary.
        
        Returns:
            Dictionary representation of iteration state
        """
        return {
            'iteration': self.iteration,
            'presenter_output': self.presenter_output,
            'reviewer_feedback': self.reviewer_feedback,
            'aggregated_feedback': self.aggregated_feedback,
            'confidence': self.confidence,
            'approved': self.approved,
            'timestamp': self.timestamp.isoformat(),
            'error': self.error
        }
    
    @classmethod
    def from_dict(cls, data: Dict) -> 'IterationState':
        """Create IterationState from dictionary.
        
        Args:
            data: Dictionary with iteration data
            
        Returns:
            IterationState instance
        """
        data_copy = data.copy()
        
        # Convert timestamp string back to datetime if needed
        if 'timestamp' in data_copy and isinstance(data_copy['timestamp'], str):
            data_copy['timestamp'] = datetime.fromisoformat(data_copy['timestamp'])
        
        return cls(**data_copy)

